# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Outline Wiki Python API
repo_url: https://github.com/eppv/outline-wiki-api
repo_name: eppv/outline-wiki-api
nav:
  - Home: index.md
  - Usage: usage.md
  - Reference:
      - Resources:
          - reference/resources/resources.md
          - Auth: reference/resources/auth.md
          - Documents: reference/resources/documents.md
          - Collections: reference/resources/collections.md
          - Users: reference/resources/users.md
          - Views: reference/resources/views.md
          - Events: reference/resources/events.md
      - Models:
          - reference/models/models.md
          - Auth: reference/models/auth.md
          - Document: reference/models/document.md
          - Collection: reference/models/collection.md
          - User: reference/models/user.md
          - View: reference/models/view.md
          - Event: reference/models/event.md
  - Contacts: contacts.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.top
    # - toc.integrate
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.share
  icon:
    logo: simple/outline
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: black
      accent: amber

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: white
      accent: orange

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search:
      lang:
        - en
        - ru
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: false
            show_root_full_path: false
            show_root_members_full_path: false
            group_by_category: true
            show_category_heading: true
            annotations_path: full
            show_signature: false
            show_submodules: true
            extensions:
              - griffe_pydantic: { schema: false }

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: Copyright &copy; 2025 Eugene Popov
